'use strict';exports.__esModule=true;var _react=require('react');var _react2=_interopRequireDefault(_react);var _propTypes=require('prop-types');var _propTypes2=_interopRequireDefault(_propTypes);var _svg4everybody=require('svg4everybody');var _svg4everybody2=_interopRequireDefault(_svg4everybody);var _enum=require('./enum');var _utils=require('./utils');function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj}}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function')}}function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError('this hasn\'t been initialised - super() hasn\'t been called')}return call&&(typeof call==='object'||typeof call==='function')?call:self}function _inherits(subClass,superClass){if(typeof superClass!=='function'&&superClass!==null){throw new TypeError('Super expression must either be null or a function, not '+typeof superClass)}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass}/*
SVG with assistive Text
If assissitive text is null, use icon
*/var Svg=function(_Component){_inherits(Svg,_Component);function Svg(){_classCallCheck(this,Svg);return _possibleConstructorReturn(this,_Component.apply(this,arguments))}Svg.prototype.renderAssistiveText=function renderAssistiveText(){if(this.props.assistiveText!==null){return _react2.default.createElement('span',{className:'slds-assistive-text'},this.props.assistiveText||(0,_utils.titleCase)(this.props.icon))}return null};Svg.prototype.render=function render(){var _props=this.props,variant=_props.variant,icon=_props.icon,className=_props.className,title=_props.title;var SLDS_URL=window.SLDS_URL||'/slds';var link=SLDS_URL+'/assets/icons/'+variant+'-sprite/svg/symbols.svg#'+icon;var props={className:className,title:title,'aria-hidden':'true'};return _react2.default.createElement(_react.Fragment,null,_react2.default.createElement('svg',props,_react2.default.createElement('use',{xmlnsXlink:'http://www.w3.org/1999/xlink',xlinkHref:link})),this.renderAssistiveText())};Svg.prototype.componentDidMount=function componentDidMount(){(0,_svg4everybody2.default)()};return Svg}(_react.Component);Svg.defaultProps={title:null,iconPosition:'left',variant:'utility'};Svg.propTypes={className:_propTypes2.default.string// variant: PropTypes.oneOf( objectValues( IconVariant ) ).isRequired,
// icon: PropTypes.oneOf([
//   ...VariantIcons,
//   ...CustomIcons,
//   ...DoctypeIcons,
//   ...StandardIcons,
//   ...UtilityIcons,
// ]),
};exports.default=Svg;