'use strict';exports.__esModule=true;exports.Branch=exports.Item=undefined;var _extends=Object.assign||function(target){for(var i=1;i<arguments.length;i++){var source=arguments[i];for(var key in source){if(Object.prototype.hasOwnProperty.call(source,key)){target[key]=source[key]}}}return target};var _react=require('react');var _react2=_interopRequireDefault(_react);var _propTypes=require('prop-types');var _propTypes2=_interopRequireDefault(_propTypes);var _lodash=require('lodash.uniqueid');var _lodash2=_interopRequireDefault(_lodash);var _Svg=require('./components/Svg');var _Svg2=_interopRequireDefault(_Svg);var _utils=require('./utils');function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj}}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function')}}function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError('this hasn\'t been initialised - super() hasn\'t been called')}return call&&(typeof call==='object'||typeof call==='function')?call:self}function _inherits(subClass,superClass){if(typeof superClass!=='function'&&superClass!==null){throw new TypeError('Super expression must either be null or a function, not '+typeof superClass)}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass}var id='treeheading'+(0,_lodash2.default)();// import Tree, { Item, Branch }  from 'react-slds/lib/Tree';
// <Tree {...props}>
//   <Branch label="Branch 1" level="1" >
//     <Item onClick={ }>SubTree Item 1</Item>
//     <Item onClick={ }>SubTree Item 2</Item>
//   </Branch>
//   <Item>Tree Item 2</Item>
//   <Item>Tree Item 3</Item>
// </Tree>
var Item=exports.Item=function(_Component){_inherits(Item,_Component);function Item(){var _temp,_this,_ret;_classCallCheck(this,Item);for(var _len=arguments.length,args=Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key]}return _ret=(_temp=(_this=_possibleConstructorReturn(this,_Component.call.apply(_Component,[this].concat(args))),_this),_this.onClick=function(e){if(typeof _this.props.onClick!=='undefined'){_this.props.onClick(e)}},_temp),_possibleConstructorReturn(_this,_ret)}Item.prototype.render=function render(){var _this2=this;var props=this.props;var cName=(0,_utils.createClassName)('slds-tree__item',props.isFocused?' slds-is-focused':'',props.isSelected?' slds-is-selected':'',props.isHovered?' slds-is-hovered':'');var buttonCname=(0,_utils.createClassName)('slds-button','slds-button_icon','slds-m-right_x-small',props.isDisabled||props.type!=='branch'?' slds-is-disabled':'');var branchProps={};var label=props.children;if(props.type==='branch'){branchProps={'aria-expanded':props.expand,className:props.className};label=props.label}return _react2.default.createElement('li',_extends({role:'treeitem','aria-level':props.level,tabIndex:props.tabIndex||null},branchProps),_react2.default.createElement('div',{className:cName,onClick:function onClick(e){return _this2.onClick(e)}},_react2.default.createElement('button',{className:buttonCname,'aria-hidden':'true',tabIndex:'-1',title:'Expand '+label},_react2.default.createElement(_Svg2.default,{className:'slds-button__icon slds-button__icon_small',variant:'utility',icon:'chevronright'}),_react2.default.createElement('span',{className:'slds-assistive-text'},props.assistiveText||null)),_react2.default.createElement('span',{className:'slds-size_1-of-1'},_react2.default.createElement('span',{className:'slds-tree__item-label slds-truncate',title:label},label))),props.type==='branch'?props.children:null)};return Item}(_react.Component);Item.propTypes={// level: PropTypes.number,
isDisabled:_propTypes2.default.bool,isFocused:_propTypes2.default.bool,isSelected:_propTypes2.default.bool,isHovered:_propTypes2.default.bool,assistiveText:_propTypes2.default.string,tabIndex:_propTypes2.default.number};Item.defaultProps={level:1,isDisabled:false,isFocused:false,isSelected:false,isHovered:false};var Branch=exports.Branch=function(_Component2){_inherits(Branch,_Component2);function Branch(props){_classCallCheck(this,Branch);var _this3=_possibleConstructorReturn(this,_Component2.call(this,props));_this3.onClick=function(e){_this3.setState({expand:!_this3.state.expand});return e};_this3.state={expand:_this3.props.isExpanded||false};return _this3}Branch.prototype.render=function render(){var _this4=this;var props=this.props;var child=validate(props,props.level);if(child.length){var itemProps={type:'branch',className:'branch',expand:this.state.expand,label:props.label,level:props.level,onClick:function onClick(e){return _this4.onClick(e)}};return _react2.default.createElement(Item,itemProps,_react2.default.createElement('ul',{role:'group'},child))}return null};return Branch}(_react.Component);Branch.propTypes={// level: PropTypes.number.isRequired,
isSelected:_propTypes2.default.bool};Branch.defaultProps={branchStyle:'branch',level:1,isSelected:false};var Tree=function(_Component3){_inherits(Tree,_Component3);function Tree(){_classCallCheck(this,Tree);return _possibleConstructorReturn(this,_Component3.apply(this,arguments))}Tree.prototype.render=function render(){return _react2.default.createElement('div',{className:'slds-tree_container',role:'application'},_react2.default.createElement('h4',{className:'slds-text-title_caps treeheading',id:id},this.props.label||null),_react2.default.createElement('ul',{className:'slds-tree',role:'tree','aria-labelledby':id},validate(this.props)))};return Tree}(_react.Component);Tree.propTypes={label:_propTypes2.default.string};Tree.defaultProps={label:''};function validate(props){var level=arguments.length>1&&arguments[1]!==undefined?arguments[1]:0;return _react2.default.Children.toArray(props.children).filter(function(n){return n.type===Item||n.type===Branch}).map(function(n,i){var cProps=_extends({},n.props,{level:level+1,key:level+'-'+i// onClick: e => console.log('x', props)
});return _react2.default.cloneElement(n,cProps)})}// isDisabled
// assistiveText
exports.default=Tree;